name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build without tests
        run: mvn clean install -DskipTests

      - name: Run backend in background
        run: |
          nohup java -jar target/product-test-1.0-SNAPSHOT.jar > backend.log 2>&1 &
          sleep 5

      - name: Wait for Backend to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8080/swagger-ui/index.html > /dev/null; then
              echo "✅ Backend is up!"
              break
            fi
            echo "⏳ Waiting... ($i)"
            sleep 2
          done

      - name: Run tests
        run: mvn test

      - name: Build Docker image
        run: docker build -t your-dockerhub-username/product-test .

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push your-dockerhub-username/product-test

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/deployment.yml
