name: Run UI Tests with Allure

on:
  push:                          # Автоматически запускать при пуше в main
    branches: [ main ]
  pull_request:                  # или при pull request
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest       # Виртуальная машина Ubuntu в облаке GitHub

    steps:
      - name: Checkout code      # 1. Склонировать твой проект
        uses: actions/checkout@v3

      - name: Set up JDK 21      # 2. Установить Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Chrome      # 3. Поставить браузер Chrome (нужен для Selenide)
        uses: browser-actions/setup-chrome@v1

      - name: Build and run tests      # 4. Запустить Maven + тесты
        run: mvn clean test

      - name: Install Allure CLI      # 5. Установить Allure через npm
        run: npm install -g allure-commandline --save-dev

      - name: Generate Allure Report  # 6. Генерировать отчёт
        run: allure generate --clean

      - name: Upload Allure Report    # 7. Загрузить отчёт как артефакт
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report/
