name: Run API Tests with Allure and publish to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Pull and Run Backend Container
        run: |
          docker run -d -p 31494:8080 --name backend uukeshov/test:1.0.0.test

      - name: Wait for Backend to be ready
        run: |
          echo "Waiting for backend to start..."
          for i in {1..30}; do
            if curl -s http://localhost:31494/swagger-ui/index.html > /dev/null; then
              echo "Backend is up!"
              break
            fi
            echo "Waiting... ($i)"
            sleep 2
          done

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Run Maven tests (headless)
        run: mvn clean test -DsuiteXmlFile=testng.xml

      - name: Install Allure CLI
        run: sudo npm install -g allure-commandline --unsafe-perm=true

      - name: Generate Allure Report
        run: allure generate target/allure-results --clean -o target/allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/allure-report
          destination_dir: allure-report
