name: Run API Tests and Publish Allure Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Set up Node.js (required for Allure CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Allure CLI
        run: npm install -g allure-commandline --unsafe-perm=true

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Pull and Run Backend Container
        run: |
          docker run -d -p 31494:8080 --name backend uukeshov/test:1.0.0.test

      - name: Wait for Backend to be ready
        run: |
          echo "Waiting for backend to start..."
          for i in {1..30}; do
            if curl -s http://localhost:31494/swagger-ui/index.html > /dev/null; then
              echo "Backend is up!"
              break
            fi
            echo "Waiting... ($i)"
            sleep 2
          done

      - name: Run API Tests
        run: mvn clean test

      - name: Generate Allure Report
        run: |
          allure generate target/allure-results --clean -o target/allure-report
          touch target/allure-report/.nojekyll

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Allure Report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages
